name: "Format With Prettier"
on: [push, pull_request]
jobs:
  prettier_format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actionsx/prettier@v2
      with:
        args: --check .
      
